import dns from 'node:dns';
dns.setServers(['1.1.1.1', '8.8.4.4']);

import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import LenisProvider from "@/components/LenisProvider";
import { Toaster } from "react-hot-toast";

const josefin = Josefin_Sans({
   subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${josefin.className} h-full antialiased`}
    >
      <body className=" min-h-full flex flex-col bg-white dark:bg-gray-900 transition-all duration-300">
        <Navbar></Navbar>
        <LenisProvider>
        {children}
        </LenisProvider>
        <Footer />
        <Toaster />
        </body>
    </html>
  );
}
